name: Build Vote
# template source: https://github.com/dockersamples/.github/blob/main/templates/call-docker-build.yaml

on:
  # we want pull requests so we can build(test) but not push to image registry
  push:
    branches:
      - 'main'
    # only build when important files change
    paths:
      - 'vote/**'
      - '.github/workflows/call-docker-build-vote.yaml'
  pull_request:
    branches:
      - 'main'
    # only build when important files change
    paths:
      - 'vote/**'
      - '.github/workflows/call-docker-build-vote.yaml'
      
permissions:
  id-token: write
  contents: read

env:
  WAYPOINT_SERVER_TOKEN: ${{ secrets.WAYPOINT_SERVER_TOKEN }}
  WAYPOINT_SERVER_ADDR: api.hashicorp.cloud:443
  #WAYPOINT_SERVER_TLS: 1
  #WAYPOINT_SERVER_TLS_SKIP_VERIFY: 1

jobs:
  call-docker-build:
    name: Vote Call Docker Build
    runs-on: ubuntu-latest
    steps:
      - name: 'Az CLI login using OIDC'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  
      - name: 'Run az commands'
        run: |
          az account show
          az group list
          
      - name: 'Checkout the branch'
        uses: actions/checkout@v2
        
      - name: Set AKS context
        id: set-context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ secrets.resource_group }}'
          cluster-name: ${{ secrets.cluster_name }}
      
      - name: Setup kubectl
        id: install-kubectl
        uses: azure/setup-kubectl@v3
        
      #- name: 'Setup Waypoint'
      #  uses: hashicorp/action-setup-waypoint
      #  with:
      #    version: '0.1.0'
          
      #- name: 'Build with Waypoint'
      #  run: |
      #    waypoint init
      #    waypoint up
