name: Build Vote
# template source: https://github.com/dockersamples/.github/blob/main/templates/call-docker-build.yaml

on:
  # we want pull requests so we can build(test) but not push to image registry
  push:
    branches:
      - 'main'
    # only build when important files change
    paths:
      - 'vote/**'
      - '.github/workflows/call-docker-build-vote.yaml'
  pull_request:
    branches:
      - 'main'
    # only build when important files change
    paths:
      - 'vote/**'
      - '.github/workflows/call-docker-build-vote.yaml'
      
permissions:
  id-token: write
  contents: read

env:
  WAYPOINT_SERVER_TOKEN: ${{ secrets.WAYPOINT_SERVER_TOKEN }}
  WAYPOINT_SERVER_ADDR: api.hashicorp.cloud:443
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  #WAYPOINT_SERVER_TLS: 1
  #WAYPOINT_SERVER_TLS_SKIP_VERIFY: 1

jobs:
  call-docker-build:
    name: Vote Call Docker Build
    runs-on: ubuntu-latest
    steps:
      - name: 'Az CLI login using OIDC'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  
      - name: 'Run az commands'
        run: |
          az account show
          az group list
          
      - name: 'Checkout the branch'
        uses: actions/checkout@v2
        
      - name: Set AKS context
        id: set-context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ secrets.resource_group }}
          cluster-name: ${{ secrets.cluster_name }}
      
      - name: Setup kubectl
        id: install-kubectl
        uses: azure/setup-kubectl@v3

      #- uses: MarcMeszaros/action-setup-waypoint@releases-api
      #  with:
      #    version: '0.8.2'
      #- run: waypoint init
      #- run: waypoint build

      - name: 'Setup Waypoint'
        uses: MarcMeszaros/action-setup-waypoint@releases-api
        with:
          version: '0.8.2'

      - name: 'Create context'
        working-directory: ./vote
        run: |
          waypoint context create \
          -server-addr=api.hashicorp.cloud:443 \
          -server-auth-token=nr9i7drhGtU2e3KrwDesmDqsxirT55V6U79eaRLPnZzLKVFKMim85Etu3o65mVpaTqz4KXi1anExNGpSUNh26DExffMD2JKqmvqZWk4XTqsXPs6nQJFrNG2qgVnwMtyhRwdwdaajRBdFd6oDX9pkdZ3EmPDouEe2wsi36YUfnwrCuoPsVyXTGX2rsNRQXBzpHYnHXQavnsaftkg49sVbt3iniUFh5jDyr65ZqHrHDW4Xx7m8WxfyG6GHN4Ja4zWCBjyaDk9JCWTVf9HwWkEwDq9UsTG9cRt6VJFAD2KefkRVRfKsKaLRiKRaPdaPAUjAAPP6rNE6Kfym96kGznqz2VCfbkXzFEn5SvKnMUgZwHTQG8CW85xLdDRbsQzRAwo61h4aZMBPFPxGg7kkXLrjBzBQ7iMH5gj1orjNL8fjhWVNEiGKkFzurMwAS4ia8QsZjaVbqf3i \
          -server-require-auth=true \
          -server-platform="hcp" \
          -set-default \
          hcp-cderue-org-cderue-project
          
      - name: 'Build with Waypoint'
        working-directory: ./vote
        run: |
          waypoint init
          waypoint up
